### ISSUE TITLE
instructions for installing ppolicy don't seem to work because distribution is lacking ldap* tools

### ISSUE THREAD

**Issue by virtuman** [dinkel/docker-openldap#7]
Hello,

I successfully installed the image and spent a good week trying to figure out the LDAP inheritance through memberOf module ... not yet accomplished but ...

I tried to install the ppolicy as the module and the instructions don't seem to play well with the tools distributed / available in container. none of the ldap\* tools seem to be available inside the container to apply that ppolicy.ldif script, could you possibly help figure out what i'm doing wrong here but inside the container ldapadd does not exist.

thank you.

**Comment by dinkel** [comment]
Hi virtuman,

Indeed, there are no client side tools like `ldapadd` installed in this docker image. This is done on purpose, because I think one should not "inject" commands into a running container.

The basic idea I was trying to describe in the documentation, would be to have the client side tools installed on the docker host machine and running the docker image with

```
docker run -d -p 389:389 -e SLAPD_PASSWORD=mysecretpassword -e SLAPD_DOMAIN=ldap.example.org dinkel/openldap
```

If you **don't** want to install client side libraries on your host machine (totally understandable and I didn't do it either), I'd suggest to use another docker image that offers client side functionality like [dinkel/docker-phpldapadmin](https://github.com/dinkel/docker-phpldapadmin). You would then run the server side docker image like this

```
docker run -d --name openldap --volumes-from your-data-container dinkel/openldap
```

and the client side image like this

```
docker run -d -p 80:80 --link openldap:openldap dinkel/phpldapadmin
```

Then from the the docker host machine use a browser on `localhost` to gain "graphical" access to your OpenLDAP instance. Connect to it using the `admin` user and _import_ the `default-policy.ldif` file.

I hope this clears things up a bit. If not, don't hesitate asking again. In the mean time I will think about make the documentation a bit more clear and precise.

_Btw: To understand the `memberof` module, it helped me a lot to use phpLDAPadmin web application, because it helps a lot in defining groups and "automagically" shows available and activated members. You could then always export LDIF data to understand the structures._

**Comment by virtuman** [comment]
I realized that you intended for the leap tools to be setup In a host or separate image as soon as sent the message, just wasn't sure if they would accept same file format as what slapd expects. Thank you for claryfying it.

As a side note - do you know if there's a way to include user in group, make that group part of another group, and then that other group as part of the group who is authorized to use a service and to see memberof in a user account that shows all inherited groups? Or what is a proper way to do that to allow only authorized service users to login to the ldap auth driven app? At first I thiight it was the memberof attribute but then I fiumd some articles that say that only direct relationship will get a memberof value.

**Comment by dinkel** [comment]
Me personally, I never had to do a group of groups scenario, but I don't see why you couldn't use `memberof` to achieve that. However it might be a bit tricky to create the correct queries ... (at least I know I woulld struggle with that).

**Comment by dinkel** [comment]
Added some clarifications in the README, therefore closing the issue.
